name: Build Documentation

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          repository: Xtr126/XtMapper-docs
          
      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
            node-version: 20
            package-manager: pnpm@latest
